version: "3.7"

services:
  sr-icecast:
    build:
      context: ../
      dockerfile: .dockerfiles/docker-sr/Dockerfile
      target: icecast
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sr-icecast:/app/icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=Password1
      - ICECAST_ADMIN_PASSWORD=Password1
      - ICECAST_PASSWORD=Password1
      - ICECAST_RELAY_PASSWORD=Password1
    ports:
      - 8000:8000
  sr-trunk-recorder:
    build:
      context: ../
      dockerfile: .dockerfiles/docker-sr/Dockerfile
      target: trunk-recorder
    restart: unless-stopped
    privileged: true
    volumes:
      - sr-audio:/app/trunk-recorder/audio
      - sr-config:/app/trunk-recorder/config
      - sr-liquid-bridge:/app/liquid-bridge/config
      - /dev/bus/usb:/dev/bus/usb
    links:
      - sr-icecast:icecast
      - sr-web-api:api
  sr-web-api:
    build:
      context: ../
      dockerfile: .dockerfiles/docker-sr/Dockerfile
      target: api
    restart: unless-stopped
    privileged: true
    volumes:
      - sr-web:/app/.certs/
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_HTTPS_PORT=8001
    ports:
      - 8001:8001
  sr-web-ui:
    build:
      context: ../
      dockerfile: .dockerfiles/docker-sr/Dockerfile
      target: ui
    restart: unless-stopped
    privileged: true
    depends_on: 
      - sr-web-api
    volumes:
      - sr-web:/app/.certs/
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_HTTPS_PORT=8000
      ports:
      - 8000:8000
# networks:
#  nginx-proxy: # Name of our shared network that containers will use
volumes:
  sr-icecast:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/zzz/docker/volumes/sr-icecast
  sr-liquidsoap:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/zzz/docker/volumes/sr-liquidsoap
  sr-audio:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/zzz/docker/volumes/sr-trunk-recorder/audio
  sr-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/zzz/docker/volumes/sr-trunk-recorder/config
  sr-liquid-bridge:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/zzz/docker/volumes/sr-liquid-bridge/config
  sr-web:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/zzz/docker/volumes/sr-web/certs
