[supervisord]
nodaemon=true

[program:liquidbridge]
command=sudo -Eu liquidsoap /app/liquid-bridge/app/SignalRadio.LiquidBridge config:/app/liquid-bridge/config/config.json server

[program:recorder]
command=/app/recorder --config=/app/trunk-recorder/config/config.json