[supervisord]
nodaemon=true

[program:liquidbridge]
command=/app/liquid-bridge/app/SignalRadio.LiquidBridge config:/app/liquid-bridge/config/config.json mode:server
user=liquidsoap
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=0

[program:recorder]
command=/app/recorder --config=/app/trunk-recorder/config/config.json
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=5