name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore SignalRadio.sln
      
    - name: Check code formatting
      run: dotnet format SignalRadio.sln --verify-no-changes --verbosity diagnostic
      
    - name: Run static analysis
      run: |
        dotnet build SignalRadio.sln --configuration Release --verbosity normal
        
    - name: Security scan with .NET security scan
      run: |
        dotnet list SignalRadio.sln package --vulnerable --include-transitive || echo "No vulnerable packages found"
